name: Push-to-EC2

on:
  push:
    branches:
      - main  # Adjust this to your default branch name

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}

      - name: Deploy Code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@54.169.93.230 "cd /home/ubuntu/github-action-pipeline  && ./deploy.sh"

